//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КурсС4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int ID_Type { get; set; }
        public int ID_Client { get; set; }
        public int Duration { get; set; }
        public int NumberOfExitsPerDay { get; set; }
        public int NumberOfDays { get; set; }
        public decimal Cost { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public int ID_Manager { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Type Type { get; set; }
    }
}
